server:
  port: 8080
spring:
  application:
    name: tbp-auth
  datasource:
    url: jdbc:h2:mem:tbpdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: mypass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: VkdTUnliUjlkaFI5WXJPY3BYa2FabjZWT0tsTUhGc1FnQ2RXV3gxWW1aT0lsUTJibGRIa2psTndqQ3h2N3Z0dg== # base64 encoded (mind. 256 byte)