server:
  port: 8080
spring:
  application:
    name: tbp-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tbp_user}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: VkdTUnliUjlkaFI5WXJPY3BYa2FabjZWT0tsTUhGc1FnQ2RXV3gxWW1aT0lsUTJibGRIa2psTndqQ3h2N3Z0dg== # base64 encoded (mind. 256 byte)