server:
  port: 8080
spring:
  application:
    name: tbp-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tbp_user}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 923662873925-hph6aaipac3q6v02nrpuduq5or50s657.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email # Die Scopes, die Sie von Google anfordern
        provider:
          google:
            issuer-uri: https://accounts.google.com # Standard für Google
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
backend:
  syncSteamApiUrl: http://192.168.86.49:31002/api/games/loadGameList
jwt:
  secret: VkdTUnliUjlkaFI5WXJPY3BYa2FabjZWT0tsTUhGc1FnQ2RXV3gxWW1aT0lsUTJibGRIa2psTndqQ3h2N3Z0dg== # base64 encoded (mind. 256 byte)